name: ifs
description: A new Flutter application.
version: 2.0.1+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  function_tree: 0.6.0
  catex: 0.0.1+6
  flutter_multi_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/